import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page.getByRole('heading', { name: 'Welcome' })).toBeVisible();
  await page.getByText('You can open products, and if').click();
  await expect(page.getByText('You can open products, and if')).toBeVisible();
  await expect(page.locator('h4')).toContainText('Welcome');
  await expect(page.getByRole('paragraph')).toContainText('You can open products, and if you are logged in (mocked), then also you can add them to your basket.');
  await expect(page.getByRole('heading', { name: 'Shop' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Home');
  await expect(page.getByRole('banner')).toContainText('Products');
  await expect(page.getByRole('banner')).toContainText('Log in');
  await page.getByRole('link', { name: 'Log in' }).click();
  await expect(page.locator('h4')).toContainText('Users');
  await expect(page.locator('h5')).toContainText('Sign in');
  await page.getByRole('heading', { name: 'Shop' }).click();
  await expect(page.locator('p', { hasText: 'Mock login using existing users' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Email' }).click();
  await page.getByRole('option', { name: 'alice@example.com' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('a');
  await expect(page.getByRole('button')).toContainText('Sign in');
  await expect(page.getByRole('button', { name: 'Sign in' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.locator('h4')).toContainText('User #1');
  await expect(page.locator('#root')).toContainText('Checkout');
  await page.getByRole('row', { name: '1 T-shirt Comfortable cotton' }).getByLabel('Remove').click();
  await page.getByRole('cell', { name: 'Remove' }).first().click();
  await page.getByRole('row', { name: '1 T-shirt Comfortable cotton' }).getByLabel('Remove').dblclick();
  await page.getByRole('button', { name: 'Remove' }).click();
  await expect(page.getByRole('paragraph')).toContainText('No items.');
  await expect(page.locator('#root')).toContainText('Checkout with Card');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await expect(page.locator('#root')).toContainText('Refresh');
  await expect(page.getByRole('banner')).toContainText('Home');
  await expect(page.getByRole('banner')).toContainText('Products');
  await expect(page.getByRole('banner')).toContainText('Basket');
  await expect(page.getByRole('banner')).toContainText('Alice');
  await expect(page.getByRole('banner')).toContainText('AliceLog out');
  await page.getByRole('link', { name: 'Products' }).click();
  await expect(page.locator('#root')).toContainText('New Product');
  await expect(page.locator('#root')).toContainText('Refresh');
  await page.getByRole('button', { name: 'New Product' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await expect(page.getByRole('heading')).toContainText('Create Product');
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('a');
  await page.getByRole('textbox', { name: 'Description' }).dblclick();
  await page.getByRole('textbox', { name: 'Description' }).fill('abc');
  await page.getByRole('spinbutton', { name: 'Price (cents)' }).click();
  await page.getByRole('spinbutton', { name: 'Price (cents)' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Stock' }).click();
  await page.getByRole('spinbutton', { name: 'Stock' }).click();
  await page.getByRole('spinbutton', { name: 'Stock' }).fill('123');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.locator('tbody')).toContainText('3');
  await expect(page.locator('tbody')).toContainText('a');
  await expect(page.locator('tbody')).toContainText('abc');
  await expect(page.locator('tbody')).toContainText('$1.00');
  await expect(page.locator('tbody')).toContainText('123');
  await expect(page.locator('thead')).toContainText('Actions');
  await expect(page.locator('thead')).toContainText('Stock');
  await expect(page.locator('thead')).toContainText('Price');
  await expect(page.locator('thead')).toContainText('Description');
  await expect(page.locator('thead')).toContainText('Name');
  await expect(page.locator('thead')).toContainText('ID');
  await page.locator('tr:nth-child(3) > td:nth-child(6) > span > .MuiButtonBase-root').click();
  await expect(page.locator('tbody')).toContainText('In basket: 1');
  await page.locator('tr:nth-child(3) > td:nth-child(6) > span > .MuiButtonBase-root').click();
  await expect(page.locator('tbody')).toContainText('In basket: 2');
  await page.getByRole('link', { name: 'Basket' }).click();
  await expect(page.getByText('abc')).toBeVisible();
  await expect(page.locator('tbody')).toContainText('a');
  await expect(page.locator('tbody')).toContainText('$1.00');
  await expect(page.locator('tbody')).toContainText('2');
  await expect(page.locator('#root')).toContainText('Checkout with Card');
  await page.getByRole('button', { name: 'Checkout with Card' }).click();
  await expect(page.getByRole('alert')).toContainText('Mock-payment processedTotal $2.00');
  await expect(page.getByRole('alert')).toContainText('Mock-payment processed');
  await expect(page.getByRole('alert')).toContainText('Total $2.00');
  await expect(page.locator('#root')).toContainText('No items.');
  await page.getByRole('button', { name: 'Checkout with Card' }).click();
  await expect(page.locator('#root')).toContainText('Bad Request');
  await expect(page.getByRole('banner')).toContainText('AliceLog out');
  await page.getByRole('button', { name: 'Alice Log out' }).click();
  await expect(page.getByRole('banner')).toContainText('Log in');
  await page.getByRole('link', { name: 'Products' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page.locator('h4')).toContainText('Welcome');
  await expect(page.getByRole('paragraph')).toContainText('You can open products, and if you are logged in (mocked), then also you can add them to your basket.');
});
